package com.zoneber.org.entity;

public class ZbUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.ID
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.USER_NAME
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.AGE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.ADDRESS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.DEPARTMENT
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.SORT_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.SEX
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.PHONE_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.PHONE_SHORT_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String phoneShortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.EMAIL
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.QQ_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String qqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.EMAIL_ORG
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String emailOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.PHONE_OTHER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String phoneOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.ACCOUNT_CODE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.JOB_STATUS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String jobStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.INSERT_USER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String insertUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.INSERT_DATE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.MODIFY_USER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USERS.MODIFY_DATE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    private String modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.ID
     *
     * @return the value of ZB_USERS.ID
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.ID
     *
     * @param id the value for ZB_USERS.ID
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.USER_NAME
     *
     * @return the value of ZB_USERS.USER_NAME
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.USER_NAME
     *
     * @param userName the value for ZB_USERS.USER_NAME
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.AGE
     *
     * @return the value of ZB_USERS.AGE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.AGE
     *
     * @param age the value for ZB_USERS.AGE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.ADDRESS
     *
     * @return the value of ZB_USERS.ADDRESS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.ADDRESS
     *
     * @param address the value for ZB_USERS.ADDRESS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.DEPARTMENT
     *
     * @return the value of ZB_USERS.DEPARTMENT
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.DEPARTMENT
     *
     * @param department the value for ZB_USERS.DEPARTMENT
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.SORT_NUM
     *
     * @return the value of ZB_USERS.SORT_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.SORT_NUM
     *
     * @param sortNum the value for ZB_USERS.SORT_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.SEX
     *
     * @return the value of ZB_USERS.SEX
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.SEX
     *
     * @param sex the value for ZB_USERS.SEX
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.PHONE_NUM
     *
     * @return the value of ZB_USERS.PHONE_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.PHONE_NUM
     *
     * @param phoneNum the value for ZB_USERS.PHONE_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.PHONE_SHORT_NUM
     *
     * @return the value of ZB_USERS.PHONE_SHORT_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getPhoneShortNum() {
        return phoneShortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.PHONE_SHORT_NUM
     *
     * @param phoneShortNum the value for ZB_USERS.PHONE_SHORT_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setPhoneShortNum(String phoneShortNum) {
        this.phoneShortNum = phoneShortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.EMAIL
     *
     * @return the value of ZB_USERS.EMAIL
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.EMAIL
     *
     * @param email the value for ZB_USERS.EMAIL
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.QQ_NUM
     *
     * @return the value of ZB_USERS.QQ_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getQqNum() {
        return qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.QQ_NUM
     *
     * @param qqNum the value for ZB_USERS.QQ_NUM
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setQqNum(String qqNum) {
        this.qqNum = qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.EMAIL_ORG
     *
     * @return the value of ZB_USERS.EMAIL_ORG
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getEmailOrg() {
        return emailOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.EMAIL_ORG
     *
     * @param emailOrg the value for ZB_USERS.EMAIL_ORG
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setEmailOrg(String emailOrg) {
        this.emailOrg = emailOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.PHONE_OTHER
     *
     * @return the value of ZB_USERS.PHONE_OTHER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getPhoneOther() {
        return phoneOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.PHONE_OTHER
     *
     * @param phoneOther the value for ZB_USERS.PHONE_OTHER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setPhoneOther(String phoneOther) {
        this.phoneOther = phoneOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.ACCOUNT_CODE
     *
     * @return the value of ZB_USERS.ACCOUNT_CODE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.ACCOUNT_CODE
     *
     * @param accountCode the value for ZB_USERS.ACCOUNT_CODE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.JOB_STATUS
     *
     * @return the value of ZB_USERS.JOB_STATUS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.JOB_STATUS
     *
     * @param jobStatus the value for ZB_USERS.JOB_STATUS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.INSERT_USER
     *
     * @return the value of ZB_USERS.INSERT_USER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.INSERT_USER
     *
     * @param insertUser the value for ZB_USERS.INSERT_USER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.INSERT_DATE
     *
     * @return the value of ZB_USERS.INSERT_DATE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.INSERT_DATE
     *
     * @param insertDate the value for ZB_USERS.INSERT_DATE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setInsertDate(String insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.MODIFY_USER
     *
     * @return the value of ZB_USERS.MODIFY_USER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.MODIFY_USER
     *
     * @param modifyUser the value for ZB_USERS.MODIFY_USER
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USERS.MODIFY_DATE
     *
     * @return the value of ZB_USERS.MODIFY_DATE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USERS.MODIFY_DATE
     *
     * @param modifyDate the value for ZB_USERS.MODIFY_DATE
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate;
    }
}