package com.zoneber.account.dao;

import java.util.List;

import com.zoneber.account.entity.ZbUserAccount;

public interface ZbUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USER_ACCOUNT
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USER_ACCOUNT
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    int insert(ZbUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USER_ACCOUNT
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    int insertSelective(ZbUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USER_ACCOUNT
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    ZbUserAccount selectByPrimaryKey(String id);
    
    /**
     * 根据用户名和密码查询
     * @param record
     * @return
     */
    List<ZbUserAccount> selectForLogin(ZbUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USER_ACCOUNT
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    int updateByPrimaryKeySelective(ZbUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USER_ACCOUNT
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    int updateByPrimaryKey(ZbUserAccount record);
}