package com.zoneber.org.dao;

import java.util.List;

import com.zoneber.org.entity.ZbUsers;

public interface ZbUsersMapper {
	List<ZbUsers> select();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USERS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USERS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    int insert(ZbUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USERS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    int insertSelective(ZbUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USERS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    ZbUsers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USERS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    int updateByPrimaryKeySelective(ZbUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZB_USERS
     *
     * @mbggenerated Fri Jun 05 20:26:14 CST 2015
     */
    int updateByPrimaryKey(ZbUsers record);
}