package com.zoneber.account.entity;

public class ZbUserAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.ID
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.USER_NAME
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.PASSWORD
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.USER_CODE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.INSERT_USER
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String insertUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.INSERT_DATE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.MODIFY_USER
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZB_USER_ACCOUNT.MODIFY_DATE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    private String modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.ID
     *
     * @return the value of ZB_USER_ACCOUNT.ID
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.ID
     *
     * @param id the value for ZB_USER_ACCOUNT.ID
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.USER_NAME
     *
     * @return the value of ZB_USER_ACCOUNT.USER_NAME
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.USER_NAME
     *
     * @param userName the value for ZB_USER_ACCOUNT.USER_NAME
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.PASSWORD
     *
     * @return the value of ZB_USER_ACCOUNT.PASSWORD
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.PASSWORD
     *
     * @param password the value for ZB_USER_ACCOUNT.PASSWORD
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.USER_CODE
     *
     * @return the value of ZB_USER_ACCOUNT.USER_CODE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.USER_CODE
     *
     * @param userCode the value for ZB_USER_ACCOUNT.USER_CODE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.STATUS
     *
     * @return the value of ZB_USER_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.STATUS
     *
     * @param status the value for ZB_USER_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.INSERT_USER
     *
     * @return the value of ZB_USER_ACCOUNT.INSERT_USER
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.INSERT_USER
     *
     * @param insertUser the value for ZB_USER_ACCOUNT.INSERT_USER
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.INSERT_DATE
     *
     * @return the value of ZB_USER_ACCOUNT.INSERT_DATE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.INSERT_DATE
     *
     * @param insertDate the value for ZB_USER_ACCOUNT.INSERT_DATE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setInsertDate(String insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.MODIFY_USER
     *
     * @return the value of ZB_USER_ACCOUNT.MODIFY_USER
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.MODIFY_USER
     *
     * @param modifyUser the value for ZB_USER_ACCOUNT.MODIFY_USER
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZB_USER_ACCOUNT.MODIFY_DATE
     *
     * @return the value of ZB_USER_ACCOUNT.MODIFY_DATE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZB_USER_ACCOUNT.MODIFY_DATE
     *
     * @param modifyDate the value for ZB_USER_ACCOUNT.MODIFY_DATE
     *
     * @mbggenerated Fri Jun 05 18:58:41 CST 2015
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate;
    }
}